name: Resume Scorer backend staging
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    - name: Create env file
      run: |
          cat << EOF > .env
          COOKIE_KEY=${{ secrets.COOKIE_KEY }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF
    - run: npm i
    - run: npm run build
    - run: npm start
